Models/ErrorViewModel.cs
using System;

namespace ImportExportExcel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Excel/SalesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ImportExportExcel.Models.Excel
{
    public class SalesModel
    {
        [Key]
        public int Id { get; set; }
        public string? VoucherId { get; set; }
        public string? Customer { get; set; }
        public DateTime? Date { get; set; }
        public double? Subtotal { get; set; }
        public double? GrandTotal { get; set; }
        public string? PrepardBy { get; set; }
        public string? FsNo { get; set; }
        public string? SalesPerson { get; set; }
        public string? SourceStore { get; set; }
    }
}

Controllers/ExcelController.cs
using ImportExportExcel.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ImportExportExcel.Controllers
{
    public class ExcelController : Controller
    {
        private readonly IConfiguration configuration;
        public ApplicationDbContext _context { get; }

        public ExcelController(IConfiguration configuration, ApplicationDbContext context)
        {
            this.configuration = configuration;
            _context = context;
        }
        public IActionResult Index()
        {
            var data = _context.SalesModels.ToList();
            return View(data);
        }

        public IActionResult ImportExcelFile()
        {
            return View();
        }

        //post excel file method
        [HttpPost]
        public IActionResult ImportExcelFile(IFormFile formfile) {
            try
            {
                    //creating local path to Excel
                    var mainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadExcelFile");
                    if (!Directory.Exists(mainPath))
                    {
                        Directory.CreateDirectory(mainPath);
                    }
                    var filePath = Path.Combine(mainPath, formfile.FileName);
                    using (FileStream stream = new FileStream(filePath, FileMode.Create))
                    {
                        formfile.CopyTo(stream);
                    }
                    var fileName = formfile.FileName;
                    string extenstion = Path.GetExtension(fileName);
                    string conString = string.Empty;

                    switch (extenstion)
                    {
                        case ".xls":
                            conString = "Provider=Microsoft.ACE.OLEDB.12.0; Data Source=" + filePath + ";Extended Properties='Excel 8.0; HDR=YES'";
                            break;
                        case ".xlsx":
                            conString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
                            break;
                    }
                    DataTable dt = new DataTable();
                    conString = string.Format(conString, filePath);
                    using (OleDbConnection conExcel = new OleDbConnection(conString))
                    {
                        using (OleDbCommand cmdExcel = new OleDbCommand())
                        {
                            using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                            {
                                cmdExcel.Connection = conExcel;
                                conExcel.Open();
                                DataTable dtExcelSchema = conExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                                string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                                cmdExcel.CommandText = "SELECT * FROM[" + sheetName + "]";
                                odaExcel.SelectCommand = cmdExcel;
                                odaExcel.Fill(dt);
                                conExcel.Close();

                            }
                        }
                    }

                    conString = configuration.GetConnectionString("DefaultConnection");
                    using (SqlConnection con = new SqlConnection(conString))
                    {
                        using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                        {
                            sqlBulkCopy.DestinationTableName = "SalesModels";
                            sqlBulkCopy.ColumnMappings.Add("VoucherId", "VoucherId");
                            sqlBulkCopy.ColumnMappings.Add("Customer", "Customer");
                            sqlBulkCopy.ColumnMappings.Add("Date", "Date");
                            sqlBulkCopy.ColumnMappings.Add("Subtotal", "Subtotal");
                            sqlBulkCopy.ColumnMappings.Add("GrandTotal", "GrandTotal");
                            sqlBulkCopy.ColumnMappings.Add("PrepardBy", "PrepardBy");
                            sqlBulkCopy.ColumnMappings.Add("FsNo", "FsNo");
                            sqlBulkCopy.ColumnMappings.Add("SalesPerson", "SalesPerson");
                            sqlBulkCopy.ColumnMappings.Add("SourceStore", "SourceStore");
                            con.Open();
                            sqlBulkCopy.WriteToServer(dt);
                            con.Close();
                        }
                    }
                    ViewBag.message = "File Imported Sucessfully, Data Saved into Database.";
                    return RedirectToAction("Index");
                
            }
            catch (Exception ex)
            {
                string msg = ex.Message;
            }
            return View();
        }
    }
}

Controllers/HomeController.cs
using ImportExportExcel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ImportExportExcel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Excel/ImportExcelFile.cshtml
@{
    ViewData["Title"] = "ImportExcelFile";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3">
            <form asp-action="ImportExcelFile" asp-controller="Excel" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label>Upload Excel File:</label>
                    <input type="file" name="FormFile" class="form-control" accept=".csv,.xls,.xlsx"/>
                </div>
                <input type="submit" class="btn btn-sm btn-primary" value="Upload"/>
            </form>
        </div>
    </div>
</div>

Views/Excel/Index.cshtml
@model IEnumerable<ImportExportExcel.Models.Excel.SalesModel>

@{ 
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-striped table-responsive-md">
                    <thead class="thead-dark">
                        <tr>
                            <th>VoucherId</th>
                            <th>Customer</th>
                            <th>Date</th>
                            <th>Subtotal</th>
                            <th>GrandTotal</th>
                            <th>PreparedBy</th>
                            <th>FsNo</th>
                            <th>Sales Person</th>
                            <th>Source Store</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var d in Model) { 
                        <tr>
                            <td>@d.VoucherId</td>
                            <td>@d.Customer</td>
                            <td>@d.Date</td>
                            <td>@d.Subtotal</td>
                            <td>@d.GrandTotal</td>
                            <td>@d.PrepardBy</td>
                            <td>@d.FsNo</td>
                            <td>@d.SalesPerson</td>
                            <td>@d.SourceStore</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImportExportExcel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImportExportExcel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ImportExportExcel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>